"""Write a Smoldyn configuration file for the particle half of a partitioned model.

Field-dependent rates use the VCell hybrid syntax that ``smoldyn.HybridGrid`` reads
(``reaction r A -> 0 0.5*B;``). The domain has reflective boundaries, matching the
PDE side's zero-flux boundaries. A surface and compartment covering the domain are
added when a 0th-order reaction needs one: Smoldyn's grid-based 0th-order creation
only runs for compartment reactions (``reaction_cmpt``).
"""
from __future__ import annotations

import numpy as np

from viva_pde_particle.grid import CartesianGrid

DOMAIN = "domain"


def _fmt(x: float) -> str:
    return repr(float(x))


def _rate(rx: dict) -> str:
    if not rx["fields"]:
        return _fmt(rx["rate_constant"])
    return "*".join([_fmt(rx["rate_constant"])] + rx["fields"]) + ";"


def _domain_surface(grid: CartesianGrid) -> list[str]:
    lines = ["start_surface walls", "action both all reflect"]
    lo = grid.origin
    hi = [o + s for o, s in zip(grid.origin, grid.size)]
    for d in range(grid.dim):
        # rect panel normal to axis d at lo/hi; its corner is the domain's low corner
        # (high face shifted to hi[d]) and it spans the other axes.
        others = [e for e in range(grid.dim) if e != d]
        for sign, pos in (("+", lo[d]), ("-", hi[d])):
            corner = list(lo)
            corner[d] = pos
            extent = [grid.size[e] for e in others]
            lines.append(f"panel rect {sign}{d} " + " ".join(_fmt(c) for c in corner) + " "
                         + " ".join(_fmt(x) for x in extent))
    lines.append("end_surface")
    center = [o + 0.5 * s for o, s in zip(grid.origin, grid.size)]
    lines += [f"start_compartment {DOMAIN}", "surface walls",
              "point " + " ".join(_fmt(c) for c in center), "end_compartment"]
    return lines


def _molecules(grid: CartesianGrid, name: str, counts: np.ndarray) -> list[str]:
    """`mol n A lo-hi ...` per grid node, placing molecules uniformly in each node's cell."""
    bounds = [grid.element_bounds(d) for d in range(grid.dim)]
    lines = []
    for idx in zip(*np.nonzero(counts)):
        n = int(counts[idx])
        ranges = []
        for d in range(grid.dim):
            i = idx[grid.dim - 1 - d]
            lo, hi = bounds[d][0][i], bounds[d][1][i]
            ranges.append(f"{_fmt(lo)}-{_fmt(hi)}" if hi > lo else _fmt(lo))
        lines.append(f"mol {n} {name} " + " ".join(ranges))
    return lines


def write_smoldyn_config(
    particles: dict,
    grid: CartesianGrid,
    initial_counts: dict[str, np.ndarray],
    time_step: float,
    seed: int,
) -> str:
    """Return the configuration text for the particle half (from :func:`partition`)."""
    if any(o < 0 for o in grid.origin):
        # Smoldyn writes position ranges as 'lo-hi', which is ambiguous for negative values.
        raise ValueError("grid origin must be non-negative for Smoldyn 'mol lo-hi' placement")
    species = list(particles["species"])
    lines = [
        "# generated by viva_pde_particle.model.smoldyn_config",
        f"dim {grid.dim}",
    ]
    for d in range(grid.dim):
        lines.append(f"boundaries {d} {_fmt(grid.origin[d])} {_fmt(grid.origin[d] + grid.size[d])} r")
    if species:
        lines.append("species " + " ".join(species))
        for s, spec in particles["species"].items():
            lines.append(f"difc {s} {_fmt(spec['diffusion'])}")
    lines += [
        "time_start 0",
        "time_stop 1e30",
        f"time_step {_fmt(time_step)}",
        f"random_seed {int(seed)}",
    ]
    reactions = particles["reactions"]
    if any(rx["order"] == 0 and rx["fields"] for rx in reactions):
        lines += _domain_surface(grid)
    for rx in reactions:
        rct = " + ".join(rx["reactants"]) or "0"
        prd = " + ".join(rx["products"]) or "0"
        keyword = f"reaction_cmpt {DOMAIN}" if (rx["order"] == 0 and rx["fields"]) else "reaction"
        lines.append(f"{keyword} {rx['name']} {rct} -> {prd} {_rate(rx)}")
    for s in species:
        lines += _molecules(grid, s, initial_counts.get(s, np.zeros(grid.shape)))
    lines.append("end_file")
    return "\n".join(lines) + "\n"
